#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
proj_dir="$(cd "$script_dir"/..; pwd)"
build_dir="$proj_dir/build"

APP_NAME="Dockerfile Variable Injector"

function print_help() {

	script_name="$(basename "$0")"
	echo "$APP_NAME - Get latest Nim version and inject it into Dockerfile_REPLACED"
	echo
	echo "Usage:"
	echo "  $script_name [OPTIONS]"
	echo "Options:"
	echo "  -h, --help              Show this usage info and exit"
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # past arg

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

NIM_VERSION="$("$script_dir/nim-version")"
echo "NIM_VERSION=\"$NIM_VERSION\""
if [ -z "$NIM_VERSION" ]
then
	exit 33
fi

GIT_VERSION="$("$script_dir/git-version" -e)"
echo "GIT_VERSION=\"$GIT_VERSION\""

mkdir -p "$build_dir"

sed \
	-e "s/^ARG NIM_VERSION=.*/ARG NIM_VERSION=\"$NIM_VERSION\"/g" \
	-e "s/^ARG GIT_VERSION=.*/ARG GIT_VERSION=\"$GIT_VERSION\"/g" \
	< "$proj_dir/Dockerfile" \
	> "$build_dir/Dockerfile_REPLACED"

