# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: Publish Docker image
on:
  push:
    branches: [ master ]
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get latest Nim version
        run: |
          export NIM_VERSION="$( \
            curl -s 'https://github.com/nim-lang/Nim/releases' | \
            grep -m1 -Eo 'archive/refs/tags/[^/]+\.tar\.gz' | \
            sed -e 's|.*/v\?||g' -e 's|.tar.gz$||g')"
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          build-args: |
            NIM_WIN_VERSION="$NIM_WIN_VERSION"
          cache-from: type=registry,ref=hoijui/nim-ci:latest
          cache-to: type=inline
          tags: hoijui/nim-ci:latest
