# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: Publish Docker image

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'scripts/build'
  release:
    types: [published]

jobs:
  publish_docker_images:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generating build/Dockerfile_REPLACED
        # ... by fetching latest Nim and Git versions,
        # and injecting them into Dockerfile
        run: |
          scripts/inject-dockerfile
          echo "############################################################"
          cat build/Dockerfile_REPLACED
          echo "############################################################"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: GitHub.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile_REPLACED
          context: .
          pull: true
          push: ${{ GitHub.event_name != 'pull_request' }}
          cache-from: type=registry,ref=hoijui/nim-ci:latest
          cache-to: type=inline
          tags: hoijui/nim-ci:latest
